- hosts: iccluster
  remote_user: root
  roles:
    - common

    # Login with Gaspar
    - ldap-login

    # Mounting shared filesystems
    - mlodata1
    - mloraw1
    # - mlo-container-scratch  # node becomes unavailable after restart

    # GPU
    - role: cuda
      cuda_version_major: 10
      cuda_version_minor: 1
    - role: cudnn
      cuda_version_major: 10
      cuda_version_minor: 1
      cudnn_version: 7.5

    # # Pytorch
    # - role: anaconda-with-pytorch
    #   cudatoolkit_version: '10.0'

    # Docker
    - role: docker-ce
      docker_version: "5:18.09.3~3-0~ubuntu-bionic"
      docker_compose_version: 1.23.2
    - role: nvidia-docker
      nvidia_docker_version: 2.0.3+docker18.09.3-1

    # Kubectl
    - kubectl
